services:
  auth-service:
    build: ./auth-service
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - postgres
  task-service:
    build: ./task-service
    ports:
      - "3002:3002"
    env_file:
      - .env
    depends_on:
      - postgres
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    env_file:
      - .env
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
  postgres:
    image: postgres:13
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo_db
